import { describe, expect, it, vi } from 'vitest';

import ReactiveState from '../../store/reactiveState';

type TestState = {
  count: number;
  profile: { name: string; tags: string[] };
};

const createState = () => {
  const state = new ReactiveState<TestState>();
  state.initialize({ count: 0, profile: { name: 'Ada', tags: [] } });
  return state;
};

const flushNotifications = () => new Promise<void>((resolve) => queueMicrotask(resolve));

describe('ReactiveState', () => {
  it('initializes and exposes a frozen top-level state', () => {
    const state = createState();

    expect(state.getState()).toEqual({ count: 0, profile: { name: 'Ada', tags: [] } });
    expect(Object.isFrozen(state.getState())).toBe(true);
  });

  it('returns the current reference by default and an independent clone on request', () => {
    const state = createState();
    const current = state.getState();
    const clone = state.getState(true);

    expect(state.getState()).toBe(current);
    expect(clone).toEqual(current);
    expect(clone).not.toBe(current);
    expect(clone.profile).not.toBe(current.profile);
  });

  it('updates state and reports paths generated by Immer', async () => {
    const state = createState();
    const subscriber = vi.fn();
    state.subscribe(subscriber);

    state.setState((draft) => {
      draft.count = 1;
      draft.profile.tags.push('typescript');
    });
    await flushNotifications();

    expect(state.getState()).toEqual({ count: 1, profile: { name: 'Ada', tags: ['typescript'] } });
    expect(subscriber).toHaveBeenCalledOnce();
    expect(subscriber.mock.calls[0][1]).toEqual(expect.arrayContaining(['count', 'profile.tags.0']));
  });

  it('batches synchronous updates and deduplicates changed paths', async () => {
    const state = createState();
    const subscriber = vi.fn();
    state.subscribe(subscriber);

    state.setState((draft) => {
      draft.count = 1;
    });
    state.setState((draft) => {
      draft.count = 2;
    });
    await flushNotifications();

    expect(subscriber).toHaveBeenCalledOnce();
    expect(subscriber).toHaveBeenCalledWith(state.getState(), ['count']);
  });

  it('uses explicitly supplied change paths', async () => {
    const state = createState();
    const subscriber = vi.fn();
    state.subscribe(subscriber);

    state.setState(
      (draft) => {
        draft.profile.name = 'Grace';
      },
      ['person.displayName'],
    );
    await flushNotifications();

    expect(subscriber).toHaveBeenCalledWith(state.getState(), ['person.displayName']);
  });

  it('does not notify or replace state when an update produces no changes', async () => {
    const state = createState();
    const original = state.getState();
    const subscriber = vi.fn();
    state.subscribe(subscriber);

    state.setState(() => undefined);
    await flushNotifications();

    expect(state.getState()).toBe(original);
    expect(subscriber).not.toHaveBeenCalled();
  });

  it('filters subscriptions by exact and descendant paths', async () => {
    const state = createState();
    const profileSubscriber = vi.fn();
    const nameSubscriber = vi.fn();
    const countSubscriber = vi.fn();
    state.subscribe(profileSubscriber, ['profile']);
    state.subscribe(nameSubscriber, ['profile.name']);
    state.subscribe(countSubscriber, ['count']);

    state.setState((draft) => {
      draft.profile.name = 'Grace';
    });
    await flushNotifications();

    expect(profileSubscriber).toHaveBeenCalledOnce();
    expect(nameSubscriber).toHaveBeenCalledOnce();
    expect(countSubscriber).not.toHaveBeenCalled();
  });

  it('unsubscribes a handler', async () => {
    const state = createState();
    const subscriber = vi.fn();
    const unsubscribe = state.subscribe(subscriber, ['count']);
    unsubscribe();

    state.setState((draft) => {
      draft.count += 1;
    });
    await flushNotifications();

    expect(subscriber).not.toHaveBeenCalled();
  });

  it('isolates subscriber errors so later subscribers are notified', async () => {
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => undefined);
    const state = createState();
    const survivor = vi.fn();
    state.subscribe(() => {
      throw new Error('subscriber failed');
    });
    state.subscribe(survivor);

    state.setState((draft) => {
      draft.count = 1;
    });
    await flushNotifications();

    expect(consoleError).toHaveBeenCalledOnce();
    expect(survivor).toHaveBeenCalledOnce();
  });

  it('provides frozen state and path collections to subscribers', async () => {
    const state = createState();
    const subscriber = vi.fn((nextState: Readonly<TestState>, paths: readonly string[]) => {
      expect(Object.isFrozen(nextState)).toBe(true);
      expect(Object.isFrozen(paths)).toBe(true);
    });
    state.subscribe(subscriber);

    state.setState((draft) => {
      draft.count = 1;
    });
    await flushNotifications();

    expect(subscriber).toHaveBeenCalledOnce();
  });

  it('destroy removes subscriptions, including a queued notification', async () => {
    const state = createState();
    const subscriber = vi.fn();
    state.subscribe(subscriber);
    state.setState((draft) => {
      draft.count = 1;
    });

    state.destroy();
    await flushNotifications();

    expect(subscriber).not.toHaveBeenCalled();
  });

  it('debug logs updates and returns the same instance', async () => {
    vi.spyOn(console, 'groupCollapsed').mockImplementation(() => undefined);
    vi.spyOn(console, 'log').mockImplementation(() => undefined);
    vi.spyOn(console, 'groupEnd').mockImplementation(() => undefined);
    const state = createState();

    expect(state.debug('Session')).toBe(state);
    state.setState((draft) => {
      draft.count = 1;
    });
    await flushNotifications();

    expect(console.groupCollapsed).toHaveBeenCalledWith('%cSession Update', 'color: #4CAF50; font-weight: bold;');
    expect(console.log).toHaveBeenCalledWith('Changed Paths:', ['count']);
    expect(console.log).toHaveBeenCalledWith('New State:', state.getState());
  });

  it.todo('notifies a child-path subscriber when its parent object is replaced');
  it.todo('deeply freezes nested values immediately after initialization');
});
